log4j:
  rootCategory: INFO, CONSOLE

# CONSOLE is set to be a ConsoleAppender using a PatternLayout.
  appender:
    CONSOLE: org.apache.log4j.ConsoleAppender
      layout: org.apache.log4j.PatternLayout
        ConversionPattern: ${LOG_PATTERN}

# ------ LOGGING SETTINGS ------ #
#-- logging levels controlled by logging.level and then appending the package name to it. LEVELS available: DEBUG, INFO, TRACE, ERROR, FATAL
logging:
  level:
    org:
      hibernate: ERROR
    demo: DEBUG
#-- the below line directs logging to a specific file
  file: logs/server.log

# ------ SERVER SETTINGS ------ #
server.port: 8080


# ------ SECURITY SETTINGS -----#
#-- the line below is used to change the default user's (user) password to a static value.
#-- if the value is not provided, then the app will generate a random password on each startup (the system will printout the generated password on startup)
security.user.password: password


# ------ DYNAMIC VARIABLES ---- #
maincontroller.default.error.message: Something went wrong